django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.static import serve
from courses.views import CourseDetailView,CourseListView, Course1View, Course1_detailDetailView
from blog.views import PostListView, post_detail

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', PostListView.as_view(), name='index'),
    #path('course/', CourseListView.as_view(), name='course'),
    path('crash_course/', CourseListView.as_view(), name='crash_course'),
    path('course1/', Course1View.as_view(), name='course1'),
    path('<slug:post>/', post_detail, name='post_detail'),
   # path('<slug:slug>', post_detail, name='post_detail'),
    path('course/<int:pk>',CourseDetailView.as_view(), name='crash_course_detail'),
    path('course1/<int:pk>/',Course1_detailDetailView.as_view(), name='course1_detail'),
    url(r'^download/(P<path>.)$', serve,
        {'document_root': settings.MEDIA_ROOT}),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from tinymce import HTMLField
from django_project.utils import unique_slug_generator

from django.conf import settings
from django.contrib.auth import get_user_model
from mptt.models import MPTTModel, TreeForeignKey
from django.db.models.signals import pre_save
from django.utils import timezone
from django.urls import reverse

# Create your models here.

STATUS = ((0, "Draft"), (1, "Publish"))

User = get_user_model()


class PostView(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username



    @property
    def view_count(self):
        return PostView.objects.filter(post=self).count()



class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField()


    def __str__(self):
        return self.user.username



class Post(models.Model):
    class NewManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(status='published')

    options = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=250, blank=True, unique_for_date='publish')
    overview = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    # comment_count =models.IntegerField(default=0)
    # view_count =models.IntegerField(default=0)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    thumbnail = models.ImageField()
    content = HTMLField('content')
    previous_post = models.ForeignKey(
        'self', related_name='previous', on_delete=models.SET_NULL, blank=True, null=True)
    next_post = models.ForeignKey(
        'self', related_name='next', on_delete=models.SET_NULL, blank=True, null=True)
    
    status = models.CharField(max_length=10, choices=options, default='draft')
    objects = models.Manager()  # default manager
    newmanager = NewManager()  # custom manager
    #   comments = GenericRelation(Comment)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post_detail', args=[self.slug])





def slug_generator(sender, instance, *args, **kwargs):
    """ Generate unique slug """
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(slug_generator, sender=Post)



class Comment(MPTTModel):
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    name = models.CharField(max_length=50)
    content = models.TextField()
    publish = models.DateTimeField(auto_now_add=True)
    email = models.EmailField()
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    class MPTTMeta:
        order_insertion_by = ['publish']

    class Meta:
        ordering = ['tree_id', 'lft']

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from tinymce import TinyMCE
from .models import Post, Comment
from mptt.forms import TreeNodeChoiceField



class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class PostForm(forms.ModelForm):
    content = forms.CharField(
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 30, 'rows': 10}
        )
    )

    class Meta:
        model = Post
        fields = '__all__'


class NewCommentForm(forms.ModelForm):
    parent = TreeNodeChoiceField(queryset=Comment.objects.all())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['parent'].widget.attrs.update(
            {'class': 'd-none'})
        self.fields['parent'].label = ''
        self.fields['parent'].required = False

    class Meta:
        model = Comment
        fields = ('name', 'parent', 'content')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'col-sm-12'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
        }

    def save(self, *args, **kwargs):
        Comment.objects.rebuild()
        return super(NewCommentForm, self).save(*args, **kwargs)

blog/views.py
from .models import Post
from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.shortcuts import HttpResponseRedirect
from .forms import NewCommentForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.


class PostListView(ListView):
    model = Post
    template_name = 'index.html'
    context_object_name = 'posts'
    ordering = ['-publish']
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        most_recent = Post.objects.order_by('-publish')[:5]
        context['most_recent'] = most_recent
        return context








    # class PostDetailView(DetailView):
     #model = Post
    #template_name = 'post_detail.html'
    #context_object_name = 'post'







#def post_detail(request, id):
 #   post = Post.objects.get(id=id)
  #  form = CommentForm()
   # if request.method == 'POST':
    #    form = CommentForm(request.POST)
     #   if form.is_valid():
      #      comment = Comment(
       #         user=form.cleaned_data["user"],
        #        content=form.cleaned_data["content"],
         #       post=post
          #  )
           # comment.save()

#    comments = Comment.objects.filter(post=post)
 #   context = {
  #      "post": post,
   #     "comments": comments,
    #    "form": form,
 #   }
  #  return render(request, "post_detail.html", context)









def post_detail(request, post):
    post = get_object_or_404(Post, slug=post, status='published')
    most_recent = Post.objects.order_by('-publish')[:5]

    allcomments = post.comments.filter(status=True)
    page = request.GET.get('page', 1)

    paginator = Paginator(allcomments, 10)
    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        comments = paginator.page(1)
    except EmptyPage:
        comments = paginator.page(paginator.num_pages)

    user_comment = None

    if request.method == 'POST':
        comment_form = NewCommentForm(request.POST)
        if comment_form.is_valid():
            user_comment = comment_form.save(commit=False)
            user_comment.post = post
            user_comment.save()
            return HttpResponseRedirect('/' + post.slug)
    else:
        comment_form = NewCommentForm()

    return render(request, 'post_detail.html',
                  {'post': post, 'comments': user_comment, 'comments': comments, 'comment_form': comment_form,
                   'allcomments': allcomments, 'most_recent': most_recent, })

blog/templates/about.html
<h1>About Page</h1>



{%for post in about %}
<h1>{{ post.title}}</h1>
<p>{{post.overview}}</p>


{% endfor %}




{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="#{% static 'css/main.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark text-center">
      <div class="container">
        <a class="navbar-brand mr-4" href="home.html">Abdul Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="home.html">Home</a>
            <a class="nav-item nav-link" href="">About</a>
          </div>
            <!-- Navbar Right Side -->
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="#">Login</a>
            <a class="nav-item nav-link" href="#">Register</a>
            <a class="nav-item nav-link" href="#">Learn Programming</a>
            <a class="nav-item nav-link" href="crash_course.html">Crash Course</a>
              
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
        {% for post in index %}
          <div class="card p-2">
            <h3><a href="">{{post.title}}</a></h3>
            <p>{{post.overview}}</p>
            <img style="width: 30%;" src="#{% static 'image/agefis-13z851QZVtE-unsplash.jpg' %}" class="img-responsive">
            <p>{{post.description}}</p>
          </div>
        {%endfor%}
      <div class="col-md-4">
        <div class="content-section fixed">
          <h3>Our Sidebar</h3>
          <p class="text-muted">You can put any text here
            <ul class="list-group">
              <li class="list-group-item list-group-item-light">Latest Post</li>
              <li class="list-group-item list-group-item-light">Announcement</li>
              <li class="list-group-item list-group-item-light">Calendars</li>
              <li class="list-group-item list-group-item-light">etc</li>
            </ul>
          </p>
        </div>
      </div>
    </div>
  </main>
  <footer class="bg-dark py-5 mt-25px text-light">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="logo">
            <h6 class="text-white">Abdul Blog</h6>
          </div>
          <div class="contact-details">
            <p class="text-light">Abuja, FCT,  NIGERIA</p>
            <p class="text-light">Phone: +2348079927876</p>
            <p class="text-light">Email: <a href="mailto:info@company.com">Info@Company.com</a></p>
          </div>
        </div>
        <div class="col-md-4">
          <div class="menus d-flex">
            <ul class="list-unstyled">
              <li> <a href="#">My Account</a></li>
              <li> <a href="#">Add Listing</a></li>
              <li> <a href="#">Pricing</a></li>
              <li> <a href="#">Privacy &amp; Policy</a></li>
            </ul>
            <ul class="list-unstyled">
              <li> <a href="#">Our Partners</a></li>
              <li> <a href="#">FAQ</a></li>
              <li> <a href="#">How It Works</a></li>
              <li> <a href="#">Contact</a></li>
            </ul>
          </div>
        </div>
        <div class="col-md-4">
          <div class="latest-posts"><a href="#">
            <div class="post d-flex align-items-center">
              <div class="title"><strong>Hotels for all budgets</strong><span class="date last-meta">October 26, 2016</span></div>
              </div></a><a href="#">
              <div class="post d-flex align-items-center">
                <div class="title"><strong>Great street atrs in London</strong><span class="date last-meta">October 26, 2016</span></div>
              </div></a><a href="#">
              <div class="post d-flex align-items-center">
              <div class="title"><strong>Best coffee shops in Sydney</strong><span class="date last-meta">October 26, 2016</span></div>
            
            </div>
         </div>
        </div>
    </div>
    <div class="copyrights">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <p class="text-light">&copy; 2017. All rights reserved. Your great site.</p>
          </div>
          <div class="col-md-6 text-right">
            <pclass="text-light">Template By <a href="https://bootstrapious.com/p/bootstrap-carousel" class="text-white">Abdul</a>
                <!-- Please do not remove the backlink to Bootstrap Temple unless you purchase an attribution-free license @ Bootstrap Temple or support us at http://bootstrapious.com/donate. It is part of the license conditions. Thanks for understanding :)                         -->
            </p>
          </div>
        </div>
      </div>
    </div>
  </footer>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    
    
</body>
</html>

blog/templates/add_comment_to_post.html
{% extends 'base.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% include 'head.html'%}

<body>

    {% include "header.html"%}

    {%block content %}

    {%endblock content %}

    {% include 'footer.html' %}
    {% include 'script.html' %}
</body>

</html>

blog/templates/comment.html
{% load crispy_forms_tags %}

<div class=" col-md-8 col-sm-4 col-xs-* card mb-4  mt-3 ">
    <!-- comments -->
    {% with comments.count as total_comments %}
    <h2>{{ total_comments }} comments</h2>

    <p>
        {% endwith %} {% for comment in comments %}
    </p>
    {% endfor %} {% load mptt_tags %}

    <div>
        {% recursetree comments %}
        <div id="{{ node.id }}" class="comments" style='padding: 10px;'>
            <p class="font-weight-bold">
                {{ node.name }}
                <span class=" text-muted font-weight-normal">
                    {{ node.publish }}
                </span>
            </p>
            {{ node.content | linebreaks}}
            {% if node.level < 3 %}
            <button class="button" onclick="myFunction({{ node.id }})">Reply</button>
            {% endif %}
        </div>
        {% if not node.is_leaf_node %}
        <div class="children pl-2 pl-md-5">
            {{ children }}
        </div>
        {% endif %}
        {% endrecursetree %}
    </div>
</div>
<div class="col-md-8 col-sm-4 col-xs-* card mb-4  mt-3 ">
    <div class="card-body">
        <h3>Leave a comment</h3>
        <form method="post" style="margin-top: 1.3em;">
            {{ comment_form | crispy }} {% csrf_token %}
            <button type="Post Comment" class="btn btn-primary  btn-lg">Post Comment</button>
        </form>
    </div>
</div>

blog/templates/course.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="col-lg-12">
    <div class="container align-items-center">
      <div class="row">
        {%for cours in courses %}
            <div class="col-md-4 col-sm-12 col-xs-12 text-center">
                <h3>{{cours.title}}</h3>
                <img style="width:100%" src="{{ cours.thumbnail.url }}" class="img-thumbnail">
                <div>
                    {%if course is adminupload %}
                      <a class="btn btn-outline-info mb4" href="{{cours.adminupload.url}}"
                        download="{{cours.adminupload.url}}">Download</a>
                    {% else %}
                      <a>EmptyFile</a>
                    {%endif%}
                </div>
            </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

blog/templates/course1.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="album py-5">
  <div class="container">
    <div class="row infinite-container">
      {% for course in course1 %}
      <div class="col-lg-4 infinite-item">
        <div class="card col-md-12 shadow-sm">
          <div class="card-body">
            <h3 class="display-4" style="font-size: 30px"><a href="{% url 'course1_detail' course.pk %}">
            <h3>{{course.title}}</h3>
            </a></h3>
            <img src="{{ course1.thumbnail.url }}" class="img-thumbnail">
            <p>{{course.overview}}</p>
            <button type="button" class="btn btn-success btn-xs"><a href="{% url 'course1_detail' course.pk %}">Continue
                Reading</a></button>
          </div>
        </div>
      </div>
      {%endfor%}
      {% if page_obj.has_next %}
      <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}"></a>
      {% endif %}
      <div class="d-flex justify-content-center" style="display:none;">
        <div class="spinner-border" role="status">
          <span class="sr-only">Loading...</span>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

blog/templates/course1_detail.html
{% extends 'base.html'%}

{% load static %}

{% block content%}
{% load crispy_forms_tags %}
<div class="album py-5">
    <main>
        <div class="container">
            <div class="row">
                <div class="mx-auto">
                    <h3><div class="p-3 border bg-success">{{course.title}}</div></h3>
                    <img style ="width:60%"src="{{ course.thumbnail.url }}" class="img-thumbnail">
                    <p>{{course.content|safe}}</p>
                </div>
                <div id="disqus_thread"></div>
                <script>

                /**
                *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
                *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

                var disqus_config = function () {
                this.page.url = '{{post.get_absolute_url}}';  // Replace PAGE_URL with your page's canonical URL variable
                this.page.identifier = '{{post_id}}'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
                };
            
                (function() { // DON'T EDIT BELOW THIS LINE
                var d = document, s = d.createElement('script');
                s.src = 'https://salty-sierra-63275-herokuapp-com.disqus.com/embed.js';
                s.setAttribute('data-timestamp', +new Date());
                (d.head || d.body).appendChild(s);
                })();
                </script>
                <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                        
            </div>
        </div>
    </main>
</div>
{% endblock %}

blog/templates/crash_course.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="album py-5">
  <div class="container">
    <div class="row infinite-container">
      {% for course in crash_course %}
      <div class="col-lg-4 infinite-item">
        <div class="card col-md-12 shadow-sm">
          <div class="card-body">
            <h3 class="display-4" style="font-size: 30px"><a href="{% url 'crash_course_detail' course.pk %}">
              <h3>{{course.title}}</h3>
            </a></h3>
            <img src="{{ course.thumbnail.url }}" class="img-thumbnail">
            <p>{{course.overview}}</p>
            <button type="button" class="btn btn-success btn-xs"><a href="{% url 'crash_course_detail' course.pk %}">Continue
                Reading</a></button>
          </div>
        </div>
      </div>
      {%endfor%}
      {% if page_obj.has_next %}
      <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}"></a>
      {% endif %}
      <div class="d-flex justify-content-center" style="display:none;">
        <div class="spinner-border" role="status">
         <span class="sr-only">Loading...</span>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="/static/js/jquery-2.2.4.min.js"></script>
<script src="/static/js/jquery.waypoints.min.js"></script>
<script src="/static/js/infinite.min.js"></script>

<script>
    var infinite = new Waypoint.Infinite({
        element: $('.infinite-container')[0],
        handler: function(direction) {
        
    },
    offset: 'bottom-in-view',
    onBeforePageLoad: function () {
    $('.spinner-border').show();
    },
    onAfterPageLoad: function () {
    $('.spinner-border').hide();
    }
    
        
    });

    var mySite = "Abdul_Blog";
    alert("Welcome To " + mySite + "!");

</script>
{% endblock content %}

blog/templates/crash_course_detail.html
{% extends 'base.html'%}

{% load static %}

{% block content%}
<main>
    <div class="container">
        <div class="row">
            <div class="mx-auto">
                <h3><div class="p-3 border bg-success">{{course.title}}</div></h3>
                <img style ="width:100%"src="{{ course.thumbnail.url }}" class="img-thumbnail">
                <p>{{course.content|safe}}</p>
            </div>    
        </div>
        <div id="disqus_thread"></div>
        <script>

        /**
        *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
        *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

        var disqus_config = function () {
        this.page.url = '{{post.get_absolute_url}}';  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = '{{post_id}}'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
        };

        (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://salty-sierra-63275-herokuapp-com.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
        })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

    </div>
</main>


{% endblock %}

blog/templates/footer.html
{% load static %}

blog/templates/post_detail.html
{% extends 'base.html' %} {% block content %} {% load static %}

<div class="container">
    <div class="row">
        <div class="col-md-8  mb-4  mt-3 left  top">
            <h1>{% block title %} {{ post.title }} {% endblock title %}</h1>
            <p class=" text-muted">{{ post.author }} | {{ post.publish }}</p>
            <p class="card-text ">{{ post.content | safe }}</p>

            
        </div>
        <div class="col-md-4 col-sm-8 col-xs-8">
            <!-- Div to center the header image/name/social buttons -->
            <div class="text-center">
                <!-- Placeholder image using Placeholder.com -->
                <img style="width: 50%;" src="{% static 'image/taisiia-stupak-muyeBGUyT6A-unsplash.jpg' %}"
                    class="img-rounded" />
                <!-- Header text (Person's name) -->
                <h2>Abdulazeez</h2>
                <h5>Web Developer, DataBase Management</h5>
                <h6></h6>
                <!-- Social buttons using anchor elements and btn-primary class to style -->
                <p>
                    <a class="btn btn-primary btn-xs" href="#" role="button">Facebook</a>
                    <a class="btn btn-primary btn-xs" href="#" role="button">Twitter</a>
                    <a class="btn btn-primary btn-xs" href="#" role="button">Instagram</a>
                    <a class="btn btn-primary btn-xs" href="#" role="button">Youtube</a>
                </p>
            </div>
            <div class="col-md-14 col-sm-18 col-xs-18">
                <div class="text-center">
                    <!-- Placeholder image using Placeholder.com -->
                    <h2 style="background-color: deepskyblue;">Currently Rendining</h2>
                    {% for post in most_recent %}
                    <h5><a href="{{post.get_absolute_url}}">{{post.title}}</a></h5>
                    {%endfor%}
                </div>
            </div>

        </div>
        {% include 'comment.html' %}
    </div>
</div>






<script>
    function formExit() {
        document.getElementById("newForm").remove();
    }

    function myFunction(id) {
        if (document.contains(document.getElementById("newForm"))) {
            document.getElementById("newForm").remove();
        }

        var d1 = document.getElementById(id);
        d1.insertAdjacentHTML('afterend',
            '<form id="newForm" class="form-insert py-2" method="post"> \
                <div class="d-flex justify-content-between"><h2>Reply:</h2><div><button type="button" class="btn btn-outline-secondary" onclick="formExit()"">Close</button></div></div> \
                <label for="id_name">Name:</label> \
                <input type="text" name="name" class="col-sm-12" maxlength="50" required="" id="id_name">\
                <select name="parent" class="d-none" id="id_parentt"> \
                <option value="' + id + '" selected="' + id + '"></option> \
                </select> \
                <label for="id_content">Content:</label> \
                <textarea name="content" cols="40" rows="5" class="form-control" required id="id_content"></textarea> \
                {% csrf_token %} \
                <button type="Post Comment" class="btn btn-primary btn-lg btn-block">Post Comment</button> \
              </form>');

        //document.querySelector('#id_parentt [value="' + id + '"]').selected = true;
    }

    $('#myForm').trigger("reset");
</script>

{% endblock content %}

blog/templates/script.html
{% load static %}


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<script src='tinymce/js/tinymce/tinymce.min.js' type='text/javascript'></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>